### ISSUE TITLE
Chosen e-paper display is obsolete

### ISSUE THREAD

**Issue by systronix** [antmicro/riscv-badge-hw#1]
EG020BS011 [according to DigiKey](https://www.digikey.com/product-detail/en/pervasive-displays/EG020BS011/EG020BS011-ND/4898784?WT.srch=1&gclid=Cj0KCQiA0vnQBRDmARIsAEL0M1lP02-wY4DraNoyQxOVq_0YGg0e5YRcpQE83uuJ0-3bPqOF_soZFO0aApCMEALw_wcB) is obsolete... ??? Is there a drop-in functional alternative? There are a variety of pinouts and signals across the pervasive display line...

Pervasive recommends E2200BS021 but again [according to DigiKey](https://www.digikey.com/products/en?keywords=E2200BS021) it has not been released to production and none are available. ????

**Comment by pkatarzynski** [comment]
We have tested the E2200CS021 and you can use it as a replacement - we have reflected this in the schematics, see commit #3243242342344.
